version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 3.1
    commands:
      - echo Installing dependencies...
      - dotnet restore
  build:
    commands:
      - echo Building the application...
      - dotnet build --configuration Release --no-restore
  post_build:
    commands:
      - echo Running tests...
      - dotnet test --no-restore --verbosity normal
artifacts:
  files:
    - '**/*'
    - '!**/obj/**'
    - '!**/bin/**'
