name: Terraform CI with LocalStack

on:
  push:
    branches:
      - terra-with-git-action
  pull_request:
    branches:
      - terra-with-git-action

jobs:
  terraform-with-local-stack:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify system Python
        run: |
          which python3
          python3 --version
          pip3 --version

      - name: Install Python tools (tflocal, pre-commit, tfsec)
        run: |
          pip3 install localstack-client pre-commit tfsec

      - name: Pre-commit checks
        run: |
          pre-commit install
          pre-commit run --all-files

      - name: Start LocalStack
        run: |
          localstack status services

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Version
        run: terraform version

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan using tflocal
        run: tflocal plan

      - name: Terraform Apply using tflocal
        if: github.event_name == 'push'
        run: tflocal apply -auto-approve

      - name: Run tfsec (Terraform Security Scan)
        run: tfsec .