name: Terraform CI with LocalStack

on:
  push:
    branches:
      - terra-with-git-action
  pull_request:
    branches:
      - terra-with-git-action

jobs:
  terraform:
    runs-on: self-hosted

    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566  # Default port for all LocalStack services
        env:
          SERVICES: s3
          DEBUG: 1
        options: >-
          --health-cmd "curl -f http://localhost:4566/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Apply to LocalStack
        env:
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_DEFAULT_REGION: eu-west-1
          AWS_ENDPOINT_URL: http://localhost:4566
        run: |
          terraform plan -out=tfplan \
            -var="region=us-east-1" \
            -var="endpoint=http://localhost:4566"
          terraform apply -auto-approve tfplan