name: Terraform CI

on:
  push:
    branches:
      - terra-with-git-action
  pull_request:
    branches:
      - terra-with-git-action

jobs:
  terraform:
    runs-on: Self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate
